// Lectio · íconos del Bosque élfico (docs/lectio-temas.md §7.5): la misma cuadrícula de
// 16×16 y las mismas cuatro tintas que los del Scriptorium (icons.js), que en este mundo
// son corteza oscura (k), hoja (r), oro (g) y plata (w). Cada ícono conserva la silueta
// del Scriptorium, para que se reconozca igual, y cambia el adorno: hojas, ramas y arcos
// élficos en vez de rosetas y lacre.

export const SYLVAN = {
  play: [
    '................',
    '................',
    '.....k..........',
    '.....kk.........',
    '.....krk........',
    '..r..krrk.......',
    '.rrg.krrrk......',
    '.rrg.kwrrrk.....',
    '..rg.kwrrrk.....',
    '...g.krrrk......',
    '.....krrk.......',
    '.....krk........',
    '.....kk.........',
    '.....k..........',
    '................',
    '................',
  ],
  pause: [
    '................',
    '....r......r....',
    '...rgr....rgr...',
    '...kkkk..kkkk...',
    '...kwwk..kwwk...',
    '...kkwk..kwkk...',
    '...kwwk..kwwk...',
    '...kwkk..kkwk...',
    '...kwwk..kwwk...',
    '...kwwk..kwwk...',
    '...kkwk..kwkk...',
    '...kwwk..kwwk...',
    '...kwwk..kwwk...',
    '...kkkk..kkkk...',
    '................',
    '................',
  ],
  prev: [
    '................',
    '..r.............',
    '.rgr........k...',
    '..k........kk...',
    '..k.......krk...',
    '..k......krrk...',
    '..k.....krrrk...',
    '..kr...kwrrrk...',
    '..krr..kwrrrk...',
    '..k.....krrrk...',
    '..k......krrk...',
    '..k.......krk...',
    '..k........kk...',
    '..k.........k...',
    '..g.............',
    '................',
  ],
  next: [
    '................',
    '.............r..',
    '...k........rgr.',
    '...kk........k..',
    '...krk.......k..',
    '...krrk......k..',
    '...krrrk.....k..',
    '...krrrwk...rk..',
    '...krrrwk..rrk..',
    '...krrrk.....k..',
    '...krrk......k..',
    '...krk.......k..',
    '...kk........k..',
    '...k.........k..',
    '.............g..',
    '................',
  ],
  // Retroceder y adelantar 15 s: la flecha es una rama curva con una hoja en la punta.
  rewind: [
    '.....rr.........',
    '....rrgkkk......',
    '.....rr...kk....',
    '..........r.k...',
    '..............k.',
    '..............k.',
    '.k....k..kkk..k.',
    '.k...kk..k....k.',
    '.k....k..kk...k.',
    '.k....k....k..k.',
    '..k..kkk.kk..k..',
    '..k..........k..',
    '...k........k...',
    '....kk....kk....',
    '......kkkk......',
    '................',
  ],
  forward: [
    '.........rr.....',
    '......kkkgrr....',
    '....kk...rr.....',
    '...k.r..........',
    '.k..............',
    '.k..............',
    '.k....k..kkk..k.',
    '.k...kk..k....k.',
    '.k....k..kk...k.',
    '.k....k....k..k.',
    '..k..kkk.kk..k..',
    '..k..........k..',
    '...k........k...',
    '....kk....kk....',
    '......kkkk......',
    '................',
  ],
  // El sol entre hojas: los rayos largos son hojas.
  sun: [
    '.......r........',
    '......rgr.......',
    '..r....g....r...',
    '..rr.......rr...',
    '.....kkkkk......',
    '....kgggggk.....',
    '...kggwgggk.....',
    'rr.kgwggggk..rr.',
    'rgrkgggggggkrgr.',
    '...kgggggggk....',
    '....kgggggk.....',
    '.....kkkkk......',
    '..rr.......rr...',
    '..r....g....r...',
    '......rgr.......',
    '.......r........',
  ],
  // La luna con una estrella de oro.
  moon: [
    '................',
    '.............g..',
    '.....kk.....gwg.',
    '...kkgk......g..',
    '...kwgk.........',
    '..kwgk..........',
    '..kwggk.........',
    '.kwgggk.........',
    '.kwgggk.........',
    '..kwgggk........',
    '..kwggggkk...k..',
    '..kwggggggkkkk..',
    '...kggggggggk...',
    '....kkggggkk....',
    '......kkkk......',
    '................',
  ],
  // Ajustes: una flor de ocho pétalos de oro con el centro de hoja.
  settings: [
    '.......kk.......',
    '...kk.kggk.kk...',
    '..kggkkggkkggk..',
    '..kgggkggkgggk..',
    '...kgggkkgggk...',
    '.kkkgk.rr.kgkkk.',
    'kgggk.rrrr.kgggk',
    'kggkkrrwrrrkkggk',
    'kggkkrrrrwrkkggk',
    'kgggk.rrrr.kgggk',
    '.kkkgk.rr.kgkkk.',
    '...kgggkkgggk...',
    '..kgggkggkgggk..',
    '..kggkkggkkggk..',
    '...kk.kggk.kk...',
    '.......kk.......',
  ],
  // Revisión: el ojo, con forma de hoja (las puntas se alargan).
  review: [
    '................',
    '................',
    '................',
    '.....kkkkkk.....',
    '...kk......kk...',
    '.kk....kk....kk.',
    'k.....krrk.....k',
    'k....krggrk....k',
    '.k...krggrk...k.',
    '..k...krrk...k..',
    '...k...kk...k...',
    '....kk....kk....',
    '......kkkk......',
    '................',
    '................',
    '................',
  ],
  // El menú: tres renglones, cada uno con una hoja.
  menu: [
    '................',
    '................',
    '..rr............',
    '.rgrr.kkkkkkkkk.',
    '..r.............',
    '................',
    '................',
    '..rr............',
    '.rgrr.kkkkkkkkk.',
    '..r.............',
    '................',
    '................',
    '..rr............',
    '.rgrr.kkkkkkkkk.',
    '..r.............',
    '................',
  ],
  // La casa élfica: techo en arco ojival de hojas y muros de piedra blanca.
  home: [
    '.......g........',
    '.......k........',
    '......krk.......',
    '.....krrrk......',
    '....krrrrrk.....',
    '...krrgrrrrk....',
    '..krrrrrrgrrk...',
    '.kkkkkkkkkkkkk..',
    '..kwwwwwwwwwk...',
    '..kwwwkkkwwwk...',
    '..kwwkgggkwwk...',
    '..kwwkg.gkwwk...',
    '..kwwkg.gkwwk...',
    '..kkkkkkkkkkk...',
    '................',
    '................',
  ],
  // La puerta entre las salas: el arco de ramas con hojas.
  door: [
    '.......rr.......',
    '.....kkrrkk.....',
    '...kkrr..rrkk...',
    '..krr.kkkk.rrk..',
    '..kr.kgggrk.rk..',
    '.kr.kgggggrk.rk.',
    '.krkggggggrrkrk.',
    '.krkggggggrrkrk.',
    '.krkggggggrrkrk.',
    '.krkggggwgrrkrk.',
    '.krkggggggrrkrk.',
    '.krkggggggrrkrk.',
    '.krkggggggrrkrk.',
    '.krkggggggrrkrk.',
    'kkkkkkkkkkkkkkkk',
    '................',
  ],
  voice: [
    '................',
    '................',
    '.......k........',
    '......kk....r...',
    '.....krk.....g..',
    '....krrk..g...g.',
    'kkkkrwrk...g..g.',
    'kwwkrwrk...g..g.',
    'kwwkrwrk...g..g.',
    'kkkkrwrk...g..g.',
    '....krrk..g...g.',
    '.....krk.....g..',
    '......kk....r...',
    '.......k........',
    '................',
    '................',
  ],
  // El volumen: tallos que crecen, cada uno con su hoja.
  volume: [
    '................',
    '..............r.',
    '.............rgr',
    '.............kwk',
    '..........r..krk',
    '.........rgr.krk',
    '.........kwk.krk',
    '.......r.krk.krk',
    '......rgrkrk.krk',
    '.....kwk.krk.krk',
    '.....krk.krk.krk',
    '.kkk.krk.krk.krk',
    '.kwk.krk.krk.krk',
    '.kkk.kkk.kkk.kkk',
    '................',
    '................',
  ],
  'volume-off': [
    '................',
    '................',
    '................',
    '................',
    '................',
    '.........kk...kk',
    '.........kgk.kgk',
    '..........kgkgk.',
    '.....kkk...kgk..',
    '.....kwk..kgkgk.',
    '.....krk.kgk.kgk',
    '.kkk.krk.kk...kk',
    '.kwk.krk........',
    '.kkk.kkk........',
    '................',
    '................',
  ],
  // Instalar: la flecha de hoja baja a la bandeja.
  install: [
    '................',
    '......kkkk......',
    '......krwk......',
    '......krrk......',
    '......krrk......',
    '......krrk......',
    '...kkkkrrkkkk...',
    '....krrrrrrk....',
    '.....krrrrk.....',
    '......krrk......',
    '.kk....kk....kk.',
    '.kgk........kgk.',
    '.kgkkkkkkkkkkgk.',
    '.kggggrrrrggggk.',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  // La cuenta: una llave élfica, el ojo en forma de hoja.
  key: [
    '................',
    '................',
    '................',
    '...kk...........',
    '..krrk..........',
    '.krrgrkkkkkkkkkk',
    'krrgrrkgggggggwk',
    'krgrrrkgggggggwk',
    '.krrrkkkkkgggkgk',
    '..krk....kgkgkgk',
    '...k.....kgkkkgk',
    '.........kkk.kkk',
    '................',
    '................',
    '................',
    '................',
  ],
  // Descargar: la flecha baja a un rollo de tela. Descargado: una corona de hojas con su marca.
  download: [
    '................',
    '......kkkk......',
    '......krwk......',
    '......krrk......',
    '......krrk......',
    '...kkkkrrkkkk...',
    '....krrrrrrk....',
    '.....krrrrk.....',
    '......krrk......',
    '.......kk.......',
    '.kkkkkkkkkkkkkk.',
    'kgkwwwgwwwwgwkgk',
    'kgkwgwwwwgwwwkgk',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  downloaded: [
    '................',
    '.....rrkkrr.....',
    '...rrk....krr...',
    '..rk........kr..',
    '..k.........gk..',
    '.rk........gg.r.',
    '.k........gg..k.',
    '.k..g....gg...k.',
    '.k..gg..gg....k.',
    '.rk..gggg....kr.',
    '..k...gg.....k..',
    '..rk........kr..',
    '...rrk....krr...',
    '.....rrkkrr.....',
    '................',
    '................',
  ],
  // Las descargas: el cofre de raíz, de madera plateada con bandas de oro y una hoja.
  chest: [
    '................',
    '.......rr.......',
    '...kkkkrgkkkk...',
    '..kwwwwwrwwwwk..',
    '.kwwwwwwwwwwwwk.',
    '.kkkkkkkkkkkkkk.',
    '.kgkwwwkkwwwkgk.',
    '.kgkwwkggkwwkgk.',
    '.kgkwwkggkwwkgk.',
    '.kgkwwwkkwwwkgk.',
    '.kgkwwwwwwwwkgk.',
    '.kgkwwwwwwwwkgk.',
    '.kkkkkkkkkkkkkk.',
    '.rkk........kkr.',
    'rr............rr',
    '................',
  ],
  // Cerrar: dos ramitas cruzadas.
  close: [
    '................',
    '.r..............',
    '.rrk........kk..',
    '..krk......krk..',
    '...krk....krk...',
    '....krk..krk....',
    '.....krkkrk.....',
    '......kggk......',
    '......kggk......',
    '.....krkkrk.....',
    '....krk..krk....',
    '...krk....krk...',
    '..krk......krk..',
    '..kk........krr.',
    '..............r.',
    '................',
  ],
};
