/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Crea una cuenta */
    post: operations['AuthController_register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Inicia sesión
     * @description Devuelve el access token y deja el refresh token en una cookie httpOnly.
     */
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Renueva la sesión
     * @description Usa la cookie del refresh token (sin cuerpo), la rota y entrega un access token nuevo.
     */
    post: operations['AuthController_refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cierra la sesión actual */
    post: operations['AuthController_logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** La cuenta de la sesión actual */
    get: operations['UsersController_me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/books': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Tu biblioteca, del más reciente al más antiguo
     * @description Tus libros y los públicos que empezaste a leer.
     */
    get: operations['BooksController_list'];
    put?: never;
    /**
     * Sube un EPUB
     * @description Lo guarda y lo encola: el worker lo procesa en segundo plano. Consulta GET /books/:id hasta que status sea ready o error.
     */
    post: operations['BooksController_upload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/books/public': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Biblioteca pública, por título
     * @description Sin sesión. Con sesión, cada libro trae tu progreso.
     */
    get: operations['BooksController_listPublic'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/books/public/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Detalle de un libro público por su slug
     * @description Sin sesión.
     */
    get: operations['BooksController_publicBySlug'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/books/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Detalle de un libro con sus capítulos
     * @description Sin sesión solo para libros públicos.
     */
    get: operations['BooksController_detail'];
    put?: never;
    post?: never;
    /** Borra un libro con sus capítulos, audio y progreso */
    delete: operations['BooksController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/books/{id}/report': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Reporte del pipeline: clasificación, limpieza y advertencias */
    get: operations['BooksController_report'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/books/{id}/cover': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Portada del libro */
    get: operations['BooksController_cover'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/books/{id}/resources': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Imagen de un capítulo
     * @description path es la ruta que aparece en el HTML del capítulo (la del EPUB).
     */
    get: operations['BooksController_resource'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/chapters/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Contenido de un capítulo para leer
     * @description Con If-None-Match igual al ETag responde 304 sin cuerpo: el capítulo no se vuelve a descargar. Sin sesión solo en libros públicos.
     */
    get: operations['ChaptersController_read'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/books/{id}/progress': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Posición actual en el libro (o el inicio si no hay) */
    get: operations['ReadingProgressController_get'];
    /**
     * Guarda la posición en el libro
     * @description Gana el clientUpdatedAt más reciente: si ya había uno posterior (de otro dispositivo), no se sobrescribe y se devuelve la posición vigente.
     */
    put: operations['ReadingProgressController_save'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/chapters/{id}/audio': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Estado del audio de un capítulo con una voz
     * @description Con status ready trae las URL firmadas del MP3 y de la alineación; mientras se genera, el progreso. Sin sesión solo en libros públicos.
     */
    get: operations['AudioController_state'];
    put?: never;
    /**
     * Pide el audio de un capítulo con una voz
     * @description Reserva los caracteres del capítulo de la cuota mensual y lo encola; consulta GET hasta que status sea ready. Si ya se está generando, responde 200 con el estado (idempotente).
     */
    post: operations['AudioController_request'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/media': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Audio o alineación con URL firmada
     * @description No usa la sesión: el permiso va en la URL (la entrega GET /chapters/:id/audio). Admite Range.
     */
    get: operations['MediaController_media'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/voices': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Voces disponibles, con su muestra
     * @description La de por defecto primero.
     */
    get: operations['VoicesController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/voices/{id}/sample': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Muestra de unos segundos de una voz */
    get: operations['VoicesController_sample'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/me/usage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Consumo de TTS de este mes
     * @description remaining = quota − consumed − reserved. La cuota se reinicia el día 1 (UTC).
     */
    get: operations['UsageController_usage'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CredentialsDto: {
      /** @example lectora@example.com */
      email: string;
      /** @example una frase larga y fácil de recordar */
      password: string;
    };
    UserDto: {
      /** Format: uuid */
      id: string;
      /** @example lectora@example.com */
      email: string;
    };
    LoginResponseDto: {
      /** @description JWT para la cabecera Authorization: Bearer. Guárdalo en memoria. */
      accessToken: string;
      /**
       * @description Segundos hasta que vence.
       * @example 900
       */
      expiresIn: number;
      user: components['schemas']['UserDto'];
    };
    AccessTokenDto: {
      /** @description JWT para la cabecera Authorization: Bearer. Guárdalo en memoria. */
      accessToken: string;
      /**
       * @description Segundos hasta que vence.
       * @example 900
       */
      expiresIn: number;
    };
    MeDto: {
      /** Format: uuid */
      id: string;
      /** @example lectora@example.com */
      email: string;
      /** Format: date-time */
      createdAt: string;
    };
    UploadResponseDto: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      status: 'pending';
    };
    LibraryProgressDto: {
      /**
       * @description orderIndex del capítulo actual.
       * @example 4
       */
      chapterOrder: number;
      /**
       * @description Número del capítulo actual entre los narrativos ("Cap. 3 de 22"); 0 si aún está en los preliminares.
       * @example 3
       */
      chapterNumber: number;
      /**
       * @description Capítulos narrativos (sin portada, dedicatoria ni notas).
       * @example 22
       */
      totalChapters: number;
      /** @enum {string} */
      mode: 'reading' | 'listening';
    };
    BookSummaryDto: {
      /** Format: uuid */
      id: string;
      /** @example Marianela */
      title: string | null;
      /** @example Benito Pérez Galdós */
      author: string | null;
      /** @example es */
      language: string | null;
      /**
       * @description pending → processing → ready | error
       * @enum {string}
       */
      status: 'pending' | 'processing' | 'ready' | 'error';
      /** @description Si status = error: DRM_PROTECTED, INVALID_ARCHIVE, NO_TEXT_CONTENT… */
      errorCode: string | null;
      /** @example /api/v1/books/<id>/cover */
      coverUrl: string | null;
      /** @description Del catálogo público de Lectio (sin dueño, no se puede borrar). */
      isPublic: boolean;
      /**
       * @description Solo libros públicos: /libros/:slug.
       * @example marianela
       */
      slug: string | null;
      /** Format: date-time */
      createdAt: string;
      progress?: components['schemas']['LibraryProgressDto'] | null;
    };
    ChapterAudioDto: {
      /** @example gonzalo */
      voiceId: string;
      /** @enum {string} */
      status: 'pending' | 'processing' | 'ready' | 'error';
    };
    ChapterSummaryDto: {
      /** Format: uuid */
      id: string;
      /** @example 4 */
      orderIndex: number;
      /** @example -I- Perdido */
      title: string;
      /**
       * @description Niveles superiores del índice.
       * @example [
       *       "Capítulos"
       *     ]
       */
      ancestors: string[];
      /**
       * @description Por defecto el cliente muestra solo narrative.
       * @enum {string}
       */
      kind: 'narrative' | 'front_matter' | 'back_matter' | 'notes';
      /** @description Caracteres de narración (lo que cuenta para la cuota). */
      characterCount: number;
      sentenceCount: number;
      /** @description Audio pedido para este capítulo, por voz. */
      audio: components['schemas']['ChapterAudioDto'][];
    };
    BookDetailDto: {
      /** Format: uuid */
      id: string;
      /** @example Marianela */
      title: string | null;
      /** @example Benito Pérez Galdós */
      author: string | null;
      /** @example es */
      language: string | null;
      /**
       * @description pending → processing → ready | error
       * @enum {string}
       */
      status: 'pending' | 'processing' | 'ready' | 'error';
      /** @description Si status = error: DRM_PROTECTED, INVALID_ARCHIVE, NO_TEXT_CONTENT… */
      errorCode: string | null;
      /** @example /api/v1/books/<id>/cover */
      coverUrl: string | null;
      /** @description Del catálogo público de Lectio (sin dueño, no se puede borrar). */
      isPublic: boolean;
      /**
       * @description Solo libros públicos: /libros/:slug.
       * @example marianela
       */
      slug: string | null;
      /** Format: date-time */
      createdAt: string;
      progress?: components['schemas']['LibraryProgressDto'] | null;
      pipelineVersion: number | null;
      /** @description Vacío hasta que el libro está ready. */
      chapters: components['schemas']['ChapterSummaryDto'][];
    };
    SentenceDto: {
      /** @description Clave de sincronización entre lectura y audio. */
      index: number;
      /** @description Bloque del HTML (atributo data-b); -1 = anuncio del capítulo. */
      blockIndex: number;
      /** @description Inicio [start, end) dentro del texto del bloque. */
      start: number;
      end: number;
      /** @description false = la oración no se narra (número de página, cita…). */
      narrated: boolean;
    };
    NoteDto: {
      /** @example fn3 */
      id: string;
      /** @example <p>…</p> */
      html: string;
    };
    ChapterDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      bookId: string;
      orderIndex: number;
      title: string;
      ancestors: string[];
      /** @enum {string} */
      kind: 'narrative' | 'front_matter' | 'back_matter' | 'notes';
      /** @description HTML sanitizado: bloques con data-b, llamadas a nota como <a data-lectio-note>, imágenes con la ruta del EPUB (ver GET /books/:id/resources). */
      contentHtml: string;
      sentences: components['schemas']['SentenceDto'][];
      notes: components['schemas']['NoteDto'][];
    };
    SaveProgressDto: {
      /** Format: uuid */
      chapterId: string;
      /**
       * @description Índice de la oración (Chapter.sentences[].index).
       * @example 143
       */
      sentenceIndex: number;
      /** @enum {string} */
      mode: 'reading' | 'listening';
      /**
       * Format: date-time
       * @description Cuándo estuvo el usuario en esa posición (no cuándo se envía).
       * @example 2026-09-28T09:58:12Z
       */
      clientUpdatedAt: string;
    };
    PositionDto: {
      /** Format: uuid */
      chapterId: string | null;
      sentenceIndex: number;
      /** @enum {string} */
      mode: 'reading' | 'listening';
      /** Format: date-time */
      clientUpdatedAt: string | null;
    };
    SaveProgressResponseDto: {
      /** @description false: había un progreso más reciente (de otro dispositivo). */
      applied: boolean;
      /** Format: date-time */
      clientUpdatedAt?: string;
      /** @description La posición vigente, si no se aplicó. */
      current?: components['schemas']['PositionDto'];
    };
    RequestAudioDto: {
      /**
       * @description Perfil de voz (GET /voices). Si se omite, el de por defecto del idioma del libro.
       * @example gonzalo
       */
      voiceId?: string;
    };
    QuotaDto: {
      /** @example 181550 */
      remaining: number;
    };
    AudioRequestResponseDto: {
      /** Format: uuid */
      chapterId: string;
      /** @example gonzalo */
      voiceId: string;
      /** @enum {string} */
      status: 'pending' | 'processing';
      /** @description Solo al crear la solicitud (202). */
      quota?: components['schemas']['QuotaDto'];
    };
    AudioProgressDto: {
      /**
       * @description Unidades de voz sintetizadas.
       * @example 42
       */
      done: number;
      /**
       * @description 0 mientras el worker no lo toma.
       * @example 180
       */
      total: number;
    };
    AudioStateDto: {
      /** Format: uuid */
      chapterId: string;
      /** @example gonzalo */
      voiceId: string;
      /** @enum {string} */
      status: 'none' | 'pending' | 'processing' | 'ready' | 'error';
      /** @description Solo en pending/processing. */
      progress: components['schemas']['AudioProgressDto'] | null;
      /** @description URL firmada; admite Range (206). */
      audioUrl: string | null;
      /** @description URL firmada del alignment.json. */
      alignmentUrl: string | null;
      /**
       * Format: date-time
       * @description Vencimiento de las URL.
       */
      expiresAt: string | null;
      /** @example 245310 */
      durationMs: number | null;
      /** @example edge */
      provider: string | null;
      /** @description El perfil de voz o la narración del capítulo cambiaron desde que se generó; se puede pedir de nuevo. Mientras tanto se sigue pudiendo escuchar. */
      outdated: boolean;
      /**
       * @description voice: cambió el perfil de voz (regenerarlo se cobra). narration: el libro se reprocesó y cambió lo que se narra (regenerarlo es gratis).
       * @enum {string|null}
       */
      outdatedReason: 'voice' | 'narration' | null;
    };
    VoiceDto: {
      /** @example gonzalo */
      id: string;
      /** @example Gonzalo */
      name: string;
      /** @example es */
      language: string;
      /** @description La que se usa si no se elige ninguna. */
      isDefault: boolean;
      /** @example /api/v1/voices/gonzalo/sample */
      sampleUrl: string;
    };
    UsageDto: {
      /** Format: date-time */
      periodStart: string;
      /** Format: date-time */
      resetsAt: string;
      /** @example 300000 */
      quota: number;
      /**
       * @description Cobrado este mes (audio ya generado).
       * @example 99790
       */
      consumed: number;
      /**
       * @description Reservado por el audio que se está generando.
       * @example 18660
       */
      reserved: number;
      /** @example 181550 */
      remaining: number;
      /**
       * @description Histórico, desde que existe la cuenta.
       * @example 84213
       */
      totalCharactersProcessed: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description La API, Postgres y Redis responden. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Alguna dependencia no responde. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CredentialsDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDto'];
        };
      };
      /** @description EMAIL_TAKEN: ya existe una cuenta con ese correo. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Demasiados intentos desde esta IP. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CredentialsDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginResponseDto'];
        };
      };
      /** @description INVALID_CREDENTIALS */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Demasiados intentos desde esta IP. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccessTokenDto'];
        };
      };
      /** @description INVALID_REFRESH_TOKEN o REFRESH_TOKEN_REUSED */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Sesión cerrada (también si ya lo estaba). */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeDto'];
        };
      };
      /** @description UNAUTHORIZED: falta el access token o venció. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BooksController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BookSummaryDto'][];
        };
      };
    };
  };
  BooksController_upload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /**
           * Format: binary
           * @description Archivo .epub sin DRM
           */
          file: string;
        };
      };
    };
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UploadResponseDto'];
        };
      };
      /** @description BOOK_ALREADY_EXISTS: ya lo subiste; incluye bookId. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description El archivo supera MAX_UPLOAD_MB. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BooksController_listPublic: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BookSummaryDto'][];
        };
      };
    };
  };
  BooksController_publicBySlug: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BookDetailDto'];
        };
      };
      /** @description BOOK_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BooksController_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BookDetailDto'];
        };
      };
      /** @description BOOK_FORBIDDEN: es de otra persona. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description BOOK_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BooksController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description BOOK_FORBIDDEN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description BOOK_BUSY: hay audio generándose. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BooksController_report: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description El reporte tal como lo guarda el pipeline (null si aún no termina). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BooksController_cover: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description COVER_NOT_FOUND: el libro no tiene portada. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BooksController_resource: {
    parameters: {
      query: {
        path: unknown;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description RESOURCE_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ChaptersController_read: {
    parameters: {
      query?: never;
      header?: {
        'If-None-Match'?: string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          /** @description Versión del capítulo */
          ETag?: unknown;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChapterDto'];
        };
      };
      /** @description No cambió desde el ETag enviado. */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description BOOK_FORBIDDEN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description CHAPTER_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ReadingProgressController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PositionDto'];
        };
      };
    };
  };
  ReadingProgressController_save: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SaveProgressDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SaveProgressResponseDto'];
        };
      };
      /** @description CHAPTER_NOT_IN_BOOK, SENTENCE_OUT_OF_RANGE, CLIENT_TIME_IN_FUTURE o VALIDATION_FAILED */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AudioController_state: {
    parameters: {
      query?: {
        voice?: string;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AudioStateDto'];
        };
      };
    };
  };
  AudioController_request: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RequestAudioDto'];
      };
    };
    responses: {
      /** @description Ya se estaba generando. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AudioRequestResponseDto'];
        };
      };
      /** @description Encolado. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AudioRequestResponseDto'];
        };
      };
      /** @description VOICE_NOT_AVAILABLE (incluye available) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description BOOK_FORBIDDEN o PUBLIC_BOOK_AUDIO */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description AUDIO_ALREADY_EXISTS */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description AUDIO_CONCURRENCY_LIMIT (incluye limit) o TTS_QUOTA_EXCEEDED (incluye required, remaining y resetsAt) */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MediaController_media: {
    parameters: {
      query: {
        sig: unknown;
        exp: unknown;
        key: unknown;
      };
      header?: {
        Range?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description El archivo completo. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description El tramo pedido con Range. */
      206: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description MEDIA_URL_INVALID o MEDIA_URL_EXPIRED */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  VoicesController_list: {
    parameters: {
      query?: {
        language?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VoiceDto'][];
        };
      };
    };
  };
  VoicesController_sample: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description VOICE_NOT_FOUND o VOICE_SAMPLE_NOT_READY */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsageController_usage: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UsageDto'];
        };
      };
    };
  };
}
